### PR TITLE
Fixes for protocol 691, now resourceValues

### PR DESCRIPTION
**Pull request by kamilion**
resourcePercentages -> resourceValues for health and energy in 691.

### CODE REVIEW

**Comment by wizzomafizzo** [comment]
thanks for your patch! much appreciated :)

**Comment by kamilion** [comment]
Sure. Credit goes to j4ck_no1r of SBReddit for tracking it down.
Won't deal with the new inventory tab, but eh, good enough to have it start
up now!

On Wed, Aug 26, 2015 at 1:55 AM, Callan Barrett <notifications@github.com>
wrote:

> thanks for your patch! much appreciated :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wizzomafizzo/starcheat/pull/209#issuecomment-134902712>
> .
>



-- 
Graham Cantin | (408) 890-7463

**Comment by wizzomafizzo** [comment]
oh good call i didn't even notice the new tab. that will take some gui changes unfortunately. i also noticed the appearance button doesn't work, seems to trip up on the personality/stances. anyway i'm glad too it hasn't completely died. i'll see what i can do but i've been pretty strapped for time atm :/

**Comment by kamilion** [comment]
understood, I saw the 'won't support a dev release early' in the other
issue. But a new binary roll would be nice, even if it had a Dialog("Uhh,
some stuff's broken right now: <stuff>") on startup.

On Wed, Aug 26, 2015 at 2:01 AM, Callan Barrett <notifications@github.com>
wrote:

> oh good call i didn't even notice the new tab. that will take some gui
> changes unfortunately. i also noticed the appearance button doesn't work,
> seems to trip up on the personality/stances. anyway i'm glad too it hasn't
> completely died. i'll see what i can do but i've been pretty strapped for
> time atm :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wizzomafizzo/starcheat/pull/209#issuecomment-134905125>
> .
>



-- 
Graham Cantin | (408) 890-7463

**Pull request merged**
