### PR TITLE
add Codacy linter + fixed style issue

### PR DESCRIPTION
**Pull request by chrmoritz**
* runs pylint and rubocop (ruby linter) over the source files, for results see: https://www.codacy.com/app/starcheat/starcheat/dashboard or the status of this PR
* converted the code basis to follow the pep8 style guide (was already close to it) and fix most pylint errors 
* codacy only works slowly atm because it has to poll for changes because I have not the permission to setup the webhook

### CODE REVIEW

**Comment by chrmoritz** [comment]
@wizzomafizzo Could you please take a look at this.

**Comment by wizzomafizzo** [comment]
oops sorry man i didn't think this was waiting on me. i'll get round to it soon

**Comment by wizzomafizzo** [comment]
woo! we're killing it on the style

**Comment by chrmoritz** [comment]
Its 75% quite straight forward whitespace (indent) and new lines rule changes.
The other 25% are converting all old style classes to new style classes which is recommended for Python 3 compatibility see: http://pylint-messages.wikidot.com/messages:c1001 but I can turn of the rule and revert these changes if you want.

**Comment by wizzomafizzo** [comment]
this all looks good to me, totally happy to have it included

do you know what needs to be added exactly for the webhook? i couldn't find anything on the site

**Comment by chrmoritz** [comment]
You should now have admin access to the codacy project. For the webhook either use the automatic webhook setup in the project settings or got to https://github.com/wizzomafizzo/starcheat/settings/hooks , click add webhook and `https://api.codacy.com/events/github/c327d4b13767493bb04061e001c0cf3f` as url, no secret and `Let me select individual events` Pull Request and Push.

**Comment by wizzomafizzo** [comment]
@chrmoritz sorry i'm taking so long, was pretty busy over christmas break, still catching up on everything

**Pull request merged**
