### PR TITLE
Add 1.0 Warning, Fix "Starcheat" capitalisation

### PR DESCRIPTION
**Pull request by kurisubrooks**

### CODE REVIEW

**Comment by chrmoritz** [comment]
Merged with some additons in 610cdaff18a3cb38765310bd5929e344a44c06fe. I think the lowercase `starcheat` is intended because it's consistent on how starcheat is written everywhere else.

**Comment by kurisubrooks** [comment]
We reverted the capitalisation to Starcheat for the 1.0 release.

**Comment by wizzomafizzo** [comment]
yeah it's intentional. idk if you saw my comment a few days ago but if it really bothers everyone i don't mind it being changed, but it should still be consitent

**Comment by kurisubrooks** [comment]
Starcheat 1.0 uses the proper capitalisation, so maybe we can just hold out
on the capitalisation of the Readme until 1.0 drops.

**Pull request closed without merging**
